using System;

namespace UnityEngine.Playables
{
	// Token: 0x020004B6 RID: 1206
	public interface IPlayableAsset
	{
		/// <summary>
		///   <para>Implement this method to have your asset inject playables into the given graph.</para>
		/// </summary>
		/// <param name="graph">The graph to inject playables into.</param>
		/// <param name="owner">The game object which initiated the build.</param>
		/// <returns>
		///   <para>The playable injected into the graph, or the root playable if multiple playables are injected.</para>
		/// </returns>
		// Token: 0x060038F3 RID: 14579
		PlayableHandle CreatePlayable(PlayableGraph graph, GameObject owner);

		/// <summary>
		///   <para>Duration in seconds.</para>
		/// </summary>
		// Token: 0x17000CF4 RID: 3316
		// (get) Token: 0x060038F4 RID: 14580
		double duration { get; }

		/// <summary>
		///   <para>A description of the PlayableOutputs generated by this asset.</para>
		/// </summary>
		// Token: 0x17000CF5 RID: 3317
		// (get) Token: 0x060038F5 RID: 14581
		PlayableBinding[] outputs { get; }
	}
}
