using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Playables;

namespace UnityEngine.Timeline
{
    /// <summary>
    ///   <para>Playable generated by a Timeline.</para>
    /// </summary>
    // Token: 0x0200001B RID: 27
    public class TimelinePlayable : ScriptPlayable
    {
        // Token: 0x060000C5 RID: 197 RVA: 0x0000578C File Offset: 0x0000398C
        public static TimelinePlayable Create(PlayableGraph graph, IList<TrackAsset> tracks, GameObject go, bool autoRebalance, bool createOutputs)
        {
            if (tracks == null)
            {
                throw new ArgumentNullException("Tracks list is null", "tracks");
            }
            if (go == null)
            {
                throw new ArgumentNullException("GameObject parameter is null", "go");
            }
            PlayableHandle handle =
                ScriptPlayableGraphExtensions
                    .CreateScriptPlayable<TimelinePlayable>(graph);

            TimelinePlayable timelinePlayable =
                handle.GetObject<TimelinePlayable>();

            if (timelinePlayable == null)
                return null;

            timelinePlayable.Compile(
                graph,
                tracks,
                go,
                autoRebalance,
                createOutputs);

            return timelinePlayable;
        }

        // Token: 0x060000C6 RID: 198 RVA: 0x000057F0 File Offset: 0x000039F0
        public void Compile(PlayableGraph graph, IList<TrackAsset> tracks, GameObject go, bool autoRebalance, bool createOutputs)
        {
            if (tracks == null)
            {
                throw new ArgumentNullException("Tracks list is null", "tracks");
            }
            if (go == null)
            {
                throw new ArgumentNullException("GameObject parameter is null", "go");
            }
            int maximumNumberOfIntersections = tracks.Count * 2 + tracks.Count;
            this.m_CurrentListOfActiveClips = this.m_IntervalTree.AllocateCache<RuntimeClipBase>(maximumNumberOfIntersections);
            this.m_ActiveClips = this.m_IntervalTree.AllocateCache<RuntimeClipBase>(maximumNumberOfIntersections);
            IList<TrackAsset> list = (from t in tracks
                                      where t.soloed
                                      select t).ToList<TrackAsset>();
            if (list.Count == 0)
            {
                list = tracks;
            }
            this.m_EvaluateCallbacks.Clear();
            this.m_PlayableCache.Clear();
            this.CompileTrackList(graph, list, go, createOutputs);
            if (autoRebalance)
            {
                this.m_Rebalancer = new IntervalTreeRebalancer(this.m_IntervalTree);
            }
        }

        // Token: 0x060000C7 RID: 199 RVA: 0x000058D8 File Offset: 0x00003AD8
        private void CompileTrackList(PlayableGraph graph, IEnumerable<TrackAsset> tracks, GameObject go, bool createOutputs)
        {
            foreach (TrackAsset trackAsset in tracks)
            {
                if (trackAsset.compilable)
                {
                    if (!this.m_IntervalTree.Contains(trackAsset))
                    {
                        trackAsset.SortClips();
                        this.m_IntervalTree.Add(trackAsset);
                        this.CreateTrackPlayable(graph, trackAsset, go, createOutputs);
                    }
                }
            }
        }

        // Token: 0x060000C8 RID: 200 RVA: 0x0000596C File Offset: 0x00003B6C
        private void CreateTrackOutput(PlayableGraph graph, GameObject go, TrackAsset track, PlayableHandle playable, int port)
        {
            if (!track.isSubTrack)
            {
                PlayableBinding[] outputs = track.outputs;
                foreach (PlayableBinding playableBinding in outputs)
                {
                    if (playableBinding.streamType == DirectorStreamType.Animation)
                    {
                        AnimationPlayableOutput output = AnimationPlayableGraphExtensions.CreateAnimationOutput(graph, playableBinding.streamName, null);
                        output.referenceObject = playableBinding.sourceObject;
                        output.sourcePlayable = playable;
                        output.sourceInputPort = port;
                        this.m_EvaluateCallbacks.Add(new AnimationOutputWeightProcessor(output));
                    }
                    else if (playableBinding.streamType == DirectorStreamType.Audio)
                    {
                        AudioPlayableOutput audioPlayableOutput = AudioPlayableGraphExtensions.CreateAudioOutput(graph, playableBinding.streamName, null);
                        audioPlayableOutput.referenceObject = playableBinding.sourceObject;
                        audioPlayableOutput.sourcePlayable = playable;
                        audioPlayableOutput.sourceInputPort = port;
                    }
                    else
                    {
                        if (playableBinding.streamType != DirectorStreamType.None)
                        {
                            throw new NotImplementedException("Unsupported stream type");
                        }
                        ScriptPlayableOutput scriptPlayableOutput = graph.CreateScriptOutput(playableBinding.streamName);
                        scriptPlayableOutput.referenceObject = playableBinding.sourceObject;
                        scriptPlayableOutput.sourcePlayable = playable;
                        scriptPlayableOutput.sourceInputPort = port;
                    }
                }
            }
        }

        // Token: 0x060000C9 RID: 201 RVA: 0x00005AA0 File Offset: 0x00003CA0
        private static PlayableHandle CreatePlayableGraph(PlayableGraph graph, TrackAsset asset, GameObject go, IntervalTree tree)
        {
            return asset.CreatePlayableGraph(graph, go, tree);
        }

        // Token: 0x060000CA RID: 202 RVA: 0x00005AC0 File Offset: 0x00003CC0
        private PlayableHandle CreateTrackPlayable(PlayableGraph graph, TrackAsset track, GameObject go, bool createOutputs)
        {
            PlayableHandle result;
            TimelinePlayable.ConnectionCache connectionCache;
            if (!track.compilable)
            {
                result = this;
            }
            else if (this.m_PlayableCache.TryGetValue(track, out connectionCache))
            {
                result = connectionCache.playable;
            }
            else if (track.name == "root")
            {
                result = this;
            }
            else
            {
                TrackAsset trackAsset = track.parent as TrackAsset;
                PlayableHandle playableHandle = (!(trackAsset != null)) ? this : this.CreateTrackPlayable(graph, trackAsset, go, createOutputs);
                PlayableHandle playableHandle2 = TimelinePlayable.CreatePlayableGraph(graph, track, go, this.m_IntervalTree);
                bool flag = false;
                if (!playableHandle2.IsValid())
                {
                    throw new InvalidOperationException(string.Concat(new object[]
                    {
                        track.name,
                        "(",
                        track.GetType(),
                        ") did not produce a valid playable. Use the compilable property to indicate whether the track is valid for processing"
                    }));
                }
                if (playableHandle.IsValid() && playableHandle2.IsValid())
                {
                    int inputCount = playableHandle.inputCount;
                    playableHandle.inputCount++;
                    flag = graph.Connect(playableHandle2, 0, playableHandle, inputCount);
                    playableHandle.SetInputWeight(inputCount, 1f);
                }
                if (createOutputs && flag)
                {
                    this.CreateTrackOutput(graph, go, track, playableHandle, playableHandle.inputCount - 1);
                }
                this.CacheTrack(track, playableHandle2, (!flag) ? -1 : (playableHandle.inputCount - 1), playableHandle);
                result = playableHandle2;
            }
            return result;
        }

        // Token: 0x060000CB RID: 203 RVA: 0x00005C44 File Offset: 0x00003E44
        public override void PrepareFrame(FrameData info)
        {
            if (this.m_Rebalancer != null)
            {
                this.m_Rebalancer.Rebalance();
            }
            bool forceSeek = info.evaluationType == null || info.seekOccurred;
            this.Evaluate((double)info.deltaTime, forceSeek);
        }

        // Token: 0x060000CC RID: 204 RVA: 0x00005C90 File Offset: 0x00003E90
        private void Evaluate(double deltaTime, bool forceSeek)
        {
            if (this.m_IntervalTree != null)
            {
                double time = this.handle.time;
                this.m_ActiveBit = ((this.m_ActiveBit != 0) ? 0 : 1);
                this.m_CurrentListOfActiveClips.Clear();
                this.m_IntervalTree.IntersectsWith<RuntimeClipBase>(time, this.m_ActiveBit, ref this.m_CurrentListOfActiveClips);
                for (int i = 0; i < this.m_ActiveClips.Count; i++)
                {
                    RuntimeClipBase runtimeClipBase = this.m_ActiveClips[i];
                    if (runtimeClipBase.intervalBit != this.m_ActiveBit)
                    {
                        runtimeClipBase.enable = false;
                    }
                }
                for (int j = 0; j < this.m_CurrentListOfActiveClips.Count; j++)
                {
                    this.m_CurrentListOfActiveClips[j].EvaluateAt(time, deltaTime, forceSeek);
                }
                this.m_ActiveClips.Clear();
                this.m_ActiveClips.AddRange(this.m_CurrentListOfActiveClips);
                int count = this.m_EvaluateCallbacks.Count;
                for (int k = 0; k < count; k++)
                {
                    this.m_EvaluateCallbacks[k].Evaluate();
                }
            }
        }

        // Token: 0x060000CD RID: 205 RVA: 0x00005DC0 File Offset: 0x00003FC0
        private void CacheTrack(TrackAsset track, PlayableHandle playable, int port, PlayableHandle parent)
        {
            this.m_PlayableCache[track] = new TimelinePlayable.ConnectionCache
            {
                playable = playable,
                port = port,
                parent = parent,
                evalWeight = 0f
            };
        }

        // Token: 0x04000071 RID: 113
        private IntervalTree m_IntervalTree = new IntervalTree();

        // Token: 0x04000072 RID: 114
        private List<RuntimeClipBase> m_ActiveClips = new List<RuntimeClipBase>();

        // Token: 0x04000073 RID: 115
        private List<RuntimeClipBase> m_CurrentListOfActiveClips;

        // Token: 0x04000074 RID: 116
        private int m_ActiveBit = 0;

        // Token: 0x04000075 RID: 117
        private List<ITimelineEvaluateCallback> m_EvaluateCallbacks = new List<ITimelineEvaluateCallback>();

        // Token: 0x04000076 RID: 118
        private Dictionary<TrackAsset, TimelinePlayable.ConnectionCache> m_PlayableCache = new Dictionary<TrackAsset, TimelinePlayable.ConnectionCache>();

        // Token: 0x04000077 RID: 119
        private IntervalTreeRebalancer m_Rebalancer;

        // Token: 0x0200001C RID: 28
        private struct ConnectionCache
        {
            // Token: 0x04000079 RID: 121
            public PlayableHandle playable;

            // Token: 0x0400007A RID: 122
            public int port;

            // Token: 0x0400007B RID: 123
            public PlayableHandle parent;

            // Token: 0x0400007C RID: 124
            public float evalWeight;
        }
    }
}
